import type { Ingredient, Concern } from './types'

export const ingredients: Ingredient[] = [
  {
    slug: 'ashwagandha',
    nameJa: 'アシュワガンダ',
    nameEn: 'Ashwagandha',
    evidenceRank: 'S',
    tagline: 'ストレス・コルチゾール低下への関与がメタ解析で確認されている',
    description:
      'アシュワガンダ（Withania somnifera）は、アーユルヴェーダ医学で数千年使われてきた植物由来のアダプトゲン。ストレスホルモン（コルチゾール）の低下、睡眠の質改善、抗疲労効果について、RCT複数件を統合したメタ解析でエビデンスが確認されている。',
    concerns: ['stress', 'sleep', 'fatigue'],
    papers: [
      {
        title: 'Adaptogenic and Anxiolytic Effects of Ashwagandha Root Extract in Healthy Adults',
        journal: 'Medicine (Baltimore)',
        year: 2021,
        studyType: 'meta-analysis',
        sampleSize: 590,
        durationWeeks: 8,
        keyFinding:
          'ストレス・不安スコアの有意な改善とコルチゾール関連指標への影響が複数のRCTで示されている（p<0.05）',
      },
      {
        title: 'A Randomized, Double-Blind, Placebo-Controlled Study of Safety and Efficacy of a High-Concentration Full-Spectrum Extract of Ashwagandha',
        journal: 'Indian Journal of Psychological Medicine',
        year: 2019,
        studyType: 'rct',
        sampleSize: 64,
        durationWeeks: 8,
        keyFinding:
          'プラセボ比でコルチゾール値が有意に低下（−27.9%）。ストレス・不安スコアが大幅に改善。',
      },
    ],
    dosageMin: 300,
    dosageMax: 600,
    dosageUnit: 'mg/日',
    timing: '夜間摂取が多い。朝晩2回に分けるプロトコルも研究されている',
    duration: '4〜12週間の継続で効果を確認した研究が多い',
    sideEffects: ['消化器症状（まれ）', '過剰摂取で甲状腺機能に影響する可能性'],
    contraindications: ['妊娠中・授乳中', '自己免疫疾患のある方', '甲状腺疾患のある方'],
    products: [
      {
        name: 'Ashwagandha Extract 500mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 2480,
        dosageMg: 500,
        rank: 1,
        reasonJa: '論文で使用された300〜600mgを1〜2カプセルで達成できる。NOW Foodsは品質管理が厳しく価格も適正',
        highlight: 'コスパ最強',
        monthlyCostJpy: 2480,
      },
    ],
    whoFor: [
      '仕事・育児などで慢性的なストレスを感じている',
      '夜なかなか寝付けない・眠りが浅い',
      '疲れているのに休んでも回復しない',
    ],
    heroStat: { value: '−27.9%', label: 'コルチゾール値の低下（8週間RCT）' },
    axisScores: { antiAging: 3, skin: 0, cognitive: 5, stress: 9, sleep: 7, immunity: 4, metabolism: 3 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'niacinamide',
    nameJa: 'ナイアシンアミド',
    nameEn: 'Niacinamide',
    evidenceRank: 'A',
    tagline: 'メラニン産生抑制・バリア機能改善がRCTで示されている',
    description:
      'ナイアシンアミド（ニコチンアミド）はビタミンB3の一形態。外用・経口ともに研究があり、メラニン産生の抑制、皮膚バリア機能の強化、毛穴の目立ちにくさへの寄与が複数のRCTで確認されている。忌避反応が少なく、レチノールと比べてマイルドな選択肢として位置付けられている。',
    concerns: ['skin-aging', 'spots', 'barrier'],
    papers: [
      {
        title: 'The effect of niacinamide on reducing cutaneous pigmentation and suppression of melanosome transfer',
        journal: 'British Journal of Dermatology',
        year: 2002,
        studyType: 'rct',
        sampleSize: 18,
        durationWeeks: 4,
        keyFinding:
          '外用ナイアシンアミドがメラノソームの転移を約35〜68%抑制することがin vitro・RCTで示されている',
      },
      {
        title: 'Niacinamide: A B vitamin that improves aging facial skin appearance',
        journal: 'Dermatologic Surgery',
        year: 2005,
        studyType: 'rct',
        sampleSize: 50,
        durationWeeks: 12,
        keyFinding:
          '5% ナイアシンアミドクリームがシミ・肌の黄ばみ・細かいシワの軽減に有意な効果を示した',
      },
    ],
    dosageMin: 500,
    dosageMax: 1500,
    dosageUnit: 'mg/日（経口）',
    timing: '食事と一緒が推奨。外用は1日2回が一般的',
    duration: '8〜12週間以上の継続で効果が現れる研究が多い',
    sideEffects: ['高用量（2g以上）でフラッシング（紅潮）の可能性', '消化器症状（まれ）'],
    contraindications: ['ナイアシンアレルギーのある方'],
    products: [
      {
        name: 'Niacinamide 500mg',
        brand: 'Thorne',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 3200,
        dosageMg: 500,
        rank: 1,
        reasonJa: 'Thorneは第三者検査機関による品質保証あり。経口ナイアシンアミドとして純度が高く信頼性が高い',
        highlight: '品質重視',
        monthlyCostJpy: 3200,
      },
    ],
    whoFor: [
      'シミ・くすみ・色むらが気になる',
      '毛穴の開きや肌のザラつきが気になる',
      'レチノールは刺激が強くてマイルドな成分を探している',
    ],
    heroStat: { value: '35〜68%', label: 'メラノソーム転移の抑制率（RCT）' },
    axisScores: { antiAging: 4, skin: 9, cognitive: 0, stress: 0, sleep: 0, immunity: 3, metabolism: 0 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'magnesium',
    nameJa: 'マグネシウム',
    nameEn: 'Magnesium',
    evidenceRank: 'S',
    tagline: '睡眠の質・疲労感への関与がメタ解析で確認されている',
    description:
      'マグネシウムは300以上の酵素反応に関わるミネラル。現代人の多くは食事から不足しがちとされる。睡眠の質改善・筋肉の疲労軽減・神経系の鎮静への関与がメタ解析・RCTで確認されている。',
    concerns: ['sleep', 'fatigue', 'stress'],
    papers: [
      {
        title: 'The Effect of Magnesium Supplementation on Primary Insomnia in Elderly: A Double-Blind Placebo-Controlled Clinical Trial',
        journal: 'Journal of Research in Medical Sciences',
        year: 2012,
        studyType: 'rct',
        sampleSize: 46,
        durationWeeks: 8,
        keyFinding:
          'マグネシウム補給群で睡眠時間・睡眠効率・早朝覚醒の改善が有意に確認された（p<0.05）',
      },
      {
        title: 'Magnesium supplementation improves indicators of low magnesium status and metabolic outcomes',
        journal: 'European Journal of Clinical Nutrition',
        year: 2020,
        studyType: 'meta-analysis',
        sampleSize: 1800,
        durationWeeks: 12,
        keyFinding: '欠乏状態の人への補給でインスリン抵抗性・血圧・CRP（炎症指標）の改善が確認された',
      },
    ],
    dosageMin: 200,
    dosageMax: 400,
    dosageUnit: 'mg/日',
    timing: '就寝1〜2時間前が睡眠目的では効果的とされる',
    duration: '4週間以上の継続で効果を確認した研究が多い',
    sideEffects: ['過剰摂取（500mg以上）で下痢・消化器症状'],
    contraindications: ['腎機能低下のある方（排泄能力が低下するため）'],
    products: [
      {
        name: 'Magnesium Glycinate 200mg',
        brand: 'Doctor\'s Best',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 2800,
        dosageMg: 200,
        rank: 1,
        reasonJa: 'グリシン酸マグネシウムは吸収率が最も高い形態の一つ。酸化マグネシウム（安い製品に多い）より体内利用率が高い',
        highlight: '吸収率重視',
        monthlyCostJpy: 2800,
        note: 'グリシン酸マグネシウムは吸収率が高く消化器刺激が少ない',
      },
    ],
    whoFor: [
      '寝付きが悪い・夜中に目が覚める',
      'こむら返り・筋肉のけいれんがある',
      '加工食品や外食が多い（マグネシウムが不足しやすい食生活）',
    ],
    heroStat: { value: '300以上', label: 'マグネシウムが関与する酵素反応の数' },
    axisScores: { antiAging: 3, skin: 1, cognitive: 6, stress: 7, sleep: 9, immunity: 4, metabolism: 6 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'vitamin-d',
    nameJa: 'ビタミンD',
    nameEn: 'Vitamin D',
    evidenceRank: 'S',
    tagline: '免疫機能・骨密度・慢性炎症への関与がメタ解析で確認されている',
    description:
      'ビタミンDは日光照射で皮膚が合成する脂溶性ビタミン。現代の屋内生活・日焼け止め使用で欠乏しやすい。免疫機能のサポート、骨密度維持、慢性炎症（inflammaging）の抑制への関与がメタ解析で確認されている。',
    concerns: ['immunity', 'inflammation', 'bone'],
    papers: [
      {
        title: 'Vitamin D supplementation to prevent acute respiratory tract infections: systematic review and meta-analysis',
        journal: 'BMJ',
        year: 2017,
        studyType: 'meta-analysis',
        sampleSize: 11321,
        durationWeeks: 16,
        keyFinding:
          '急性呼吸器感染症のリスクが補給群で有意に低下（OR 0.88）。欠乏状態の人でより顕著な効果',
      },
      {
        title: 'Effects of Vitamin D supplementation on musculoskeletal health: a systematic review',
        journal: 'Lancet Diabetes & Endocrinology',
        year: 2018,
        studyType: 'meta-analysis',
        sampleSize: 81000,
        keyFinding:
          '骨折リスク・転倒リスクの低減について、血中25(OH)D濃度が50nmol/L未満の人で効果が顕著',
      },
    ],
    dosageMin: 1000,
    dosageMax: 4000,
    dosageUnit: 'IU/日',
    timing: '脂溶性なので食事（脂質を含む食事）と一緒が吸収率が高い',
    duration: '継続的な摂取が必要。季節・生活習慣に応じて調整',
    sideEffects: ['過剰摂取（長期的に10,000 IU以上）で高カルシウム血症のリスク'],
    contraindications: ['高カルシウム血症の方', '特定の肉芽腫性疾患'],
    products: [
      {
        name: 'Vitamin D3 2000 IU',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1200,
        dosageMg: 50,
        rank: 1,
        reasonJa: 'D3（コレカルシフェロール）はD2より吸収率が高く、2000IUは安全域内での標準的な補充量。圧倒的なコスパ',
        highlight: 'コスパ最強',
        monthlyCostJpy: 1200,
        note: 'D3形態が吸収率が高い',
      },
    ],
    whoFor: [
      '室内勤務が多く日光にほぼ当たらない',
      '日焼け止めを日常的に使っている',
      '魚（特に脂の多い青魚）をほとんど食べない',
    ],
    heroStat: { value: '11,321名', label: 'メタ解析のエビデンス規模（BMJ）' },
    axisScores: { antiAging: 5, skin: 2, cognitive: 5, stress: 3, sleep: 3, immunity: 9, metabolism: 5 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'omega3',
    nameJa: 'オメガ3（EPA・DHA）',
    nameEn: 'Omega-3 (EPA/DHA)',
    evidenceRank: 'S',
    tagline: '慢性炎症・心血管・認知機能への関与がメタ解析で確認されている',
    description:
      'EPA（エイコサペンタエン酸）とDHA（ドコサヘキサエン酸）は青魚に多く含まれる長鎖多価不飽和脂肪酸。慢性炎症（inflammaging）の抑制、心血管リスクの低下、認知機能維持への関与が複数のメタ解析で確認されている。',
    concerns: ['inflammation', 'cognitive', 'skin-aging'],
    papers: [
      {
        title: 'Omega-3 Fatty Acids and Inflammatory Processes: From Molecules to Man',
        journal: 'Biochemical Society Transactions',
        year: 2017,
        studyType: 'meta-analysis',
        sampleSize: 5000,
        keyFinding:
          'EPA・DHAが炎症性サイトカイン（IL-6、TNF-α）を有意に低下させることが複数のRCTで確認',
      },
      {
        title: 'Association of omega-3 fatty acid supplementation with risk of major cardiovascular disease events',
        journal: 'JAMA',
        year: 2012,
        studyType: 'meta-analysis',
        sampleSize: 68680,
        keyFinding:
          '心血管死亡・心筋梗塞リスクへの有意な低下効果はなかったが、特定集団（魚をほぼ食べない層）では効果が示唆された',
      },
    ],
    dosageMin: 1000,
    dosageMax: 3000,
    dosageUnit: 'mg/日（EPA＋DHA合計）',
    timing: '食事と一緒。脂溶性なので脂質と一緒に摂ると吸収が良い',
    duration: '12週間以上の継続で炎症指標の改善を確認した研究が多い',
    sideEffects: ['魚臭・げっぷ（腸溶性コーティング製品で軽減可能）', '高用量で出血傾向が増す可能性'],
    contraindications: ['抗凝固薬（ワーファリン等）を服用中の方は医師に要相談'],
    products: [
      {
        name: 'Ultra Omega-3 500 EPA/250 DHA',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 3500,
        rank: 1,
        reasonJa: '1カプセルでEPA 500mg+DHA 250mgを達成。腸溶コーティングで魚臭いげっぷを防ぐ。第三者試験で重金属非検出確認済み',
        highlight: '品質重視',
        monthlyCostJpy: 3500,
        note: '1カプセルで EPA 500mg+DHA 250mg',
      },
    ],
    whoFor: [
      '青魚（サバ・イワシ・サーモン）をほとんど食べない',
      '関節の痛みや慢性的な炎症が気になる',
      '認知機能の維持・脳の健康に関心がある',
    ],
    heroStat: { value: '68,680名', label: 'メタ解析のエビデンス規模（JAMA）' },
    axisScores: { antiAging: 6, skin: 4, cognitive: 8, stress: 4, sleep: 3, immunity: 7, metabolism: 5 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'collagen-peptide',
    nameJa: 'コラーゲンペプチド',
    nameEn: 'Collagen Peptide',
    evidenceRank: 'A',
    tagline: '皮膚の弾力・水分量への関与がRCTで確認されている',
    description:
      'コラーゲンペプチドは加水分解により低分子化されたコラーゲン。経口摂取後、皮膚線維芽細胞への到達・刺激が動物実験およびヒトRCTで確認されている。肌の弾力・水分量・ハリへの関与が複数のRCTで示されている。',
    concerns: ['skin-aging', 'wrinkles'],
    papers: [
      {
        title: 'Oral Supplementation of Specific Collagen Peptides Has Beneficial Effects on Human Skin Physiology',
        journal: 'Skin Pharmacology and Physiology',
        year: 2014,
        studyType: 'rct',
        sampleSize: 69,
        durationWeeks: 8,
        keyFinding:
          '2.5〜5gのコラーゲンペプチド摂取群で皮膚弾力性が有意に改善（p<0.05）。高齢者でより顕著',
      },
      {
        title: 'Dietary Supplementation with Specific Collagen Peptides Has a Body Mass Index-Dependent Beneficial Effect on Cellulite Morphology',
        journal: 'Journal of Medicinal Food',
        year: 2015,
        studyType: 'rct',
        sampleSize: 105,
        durationWeeks: 26,
        keyFinding: '継続的な摂取で皮膚水分量・コラーゲン密度の有意な改善が確認された',
      },
    ],
    dosageMin: 2500,
    dosageMax: 10000,
    dosageUnit: 'mg/日',
    timing: 'いつでも可。ビタミンCと一緒に摂るとコラーゲン合成が促進される可能性',
    duration: '8週間以上の継続で効果を確認した研究が多い',
    sideEffects: ['消化器症状（まれ）', '魚由来の場合は魚アレルギーに注意'],
    contraindications: ['コラーゲン・ゼラチンにアレルギーのある方'],
    products: [
      {
        name: 'Collagen Peptides Powder',
        brand: 'Vital Proteins',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 4800,
        dosageMg: 20000,
        rank: 1,
        reasonJa: '論文で使用された2.5〜10gを1スクープで達成。無味無臭でコーヒー・スープに溶かせる。Vital Proteinsは牧草飼育牛由来で品質が高い',
        highlight: '溶けやすい',
        monthlyCostJpy: 4800,
        note: '1回20g（20,000mg）。無味無臭でドリンクに溶かせる',
      },
    ],
    whoFor: [
      '肌のハリ・弾力が落ちてきたと感じる30代以上',
      '内側から肌の老化ケアをしたい',
      'ビタミンCと組み合わせて効果を高めたい',
    ],
    heroStat: { value: '2.5〜5g', label: '皮膚弾力改善を確認した用量（RCT）' },
    axisScores: { antiAging: 3, skin: 8, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 2 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'coq10',
    nameJa: 'コエンザイムQ10',
    nameEn: 'Coenzyme Q10',
    evidenceRank: 'A',
    tagline: 'ミトコンドリア機能・酸化ストレス低減への関与がRCTで確認されている',
    description:
      'コエンザイムQ10（ユビキノン）はミトコンドリアのエネルギー産生（ATP合成）に不可欠な補酵素。加齢とともに体内合成量が低下する。疲労感の軽減、酸化ストレスの低下、心血管機能への関与がRCTで確認されている。',
    concerns: ['fatigue', 'inflammation', 'skin-aging'],
    papers: [
      {
        title: 'The Effect of Coenzyme Q10 on Morbidity and Mortality in Chronic Heart Failure',
        journal: 'JACC: Heart Failure',
        year: 2014,
        studyType: 'rct',
        sampleSize: 420,
        durationWeeks: 104,
        keyFinding: 'Q10群で主要心血管イベントが有意に減少（p=0.003）。全死亡リスクも低下',
      },
      {
        title: 'Coenzyme Q10 supplementation and exercise-induced acute muscle damage in trained athletes',
        journal: 'Nutrition Journal',
        year: 2008,
        studyType: 'rct',
        sampleSize: 22,
        durationWeeks: 2,
        keyFinding: '運動後の酸化ストレスマーカー（MDA）が補給群で有意に低下',
      },
    ],
    dosageMin: 100,
    dosageMax: 300,
    dosageUnit: 'mg/日',
    timing: '脂溶性なので油脂を含む食事と一緒。ユビキノールは吸収率が高い',
    duration: '4〜12週間の継続で効果を確認した研究が多い',
    sideEffects: ['過剰摂取で頭痛・消化器症状（まれ）'],
    contraindications: ['ワーファリン服用中の方（効果に影響する可能性）'],
    products: [
      {
        name: 'Ubiquinol QH-absorb 200mg',
        brand: 'Jarrow Formulas',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 5200,
        dosageMg: 200,
        rank: 1,
        reasonJa: 'ユビキノール（還元型）はユビキノン（酸化型）より吸収率が3〜4倍高い。40歳以上や疲労感が強い場合はユビキノールを選ぶ価値がある',
        highlight: '吸収率重視',
        monthlyCostJpy: 5200,
        note: 'ユビキノール形態（吸収率が高い）',
      },
    ],
    whoFor: [
      '40代以上で疲れやすくなったと感じる',
      'スタチン系薬を服用している（CoQ10が低下しやすい）',
      'ミトコンドリア機能の維持に関心がある',
    ],
    heroStat: { value: '2年間', label: '心血管イベント低下を確認したRCT期間' },
    axisScores: { antiAging: 7, skin: 4, cognitive: 3, stress: 2, sleep: 2, immunity: 4, metabolism: 9 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'nmn',
    nameJa: 'NMN',
    nameEn: 'Nicotinamide Mononucleotide',
    evidenceRank: 'B',
    tagline: 'NAD+値の上昇は確認されているが、臨床的効果はデータ不足',
    description:
      'NMNはNAD+（細胞のエネルギー通貨）の前駆体。動物実験では著明な抗老化効果が示されているが、ヒト臨床試験では「NAD+は上がる。しかし体の指標はほぼ変わらない」が現時点の結論。2024年のメタ解析（12RCT・n=513）でもほとんどの臨床アウトカムで有意差なし。',
    concerns: ['fatigue', 'skin-aging'],
    papers: [
      {
        title: 'The effects of NMN supplementation on metabolic outcomes in adults: a systematic review and meta-analysis',
        journal: 'Tandfonline Systematic Review',
        year: 2024,
        studyType: 'meta-analysis',
        sampleSize: 513,
        durationWeeks: 12,
        keyFinding:
          '血中NAD+は有意に上昇するが、血糖・脂質・その他代謝指標ではほぼ有意差なし。「NAD+は上がる。体は変わらない」が現時点の結論',
      },
    ],
    dosageMin: 250,
    dosageMax: 1000,
    dosageUnit: 'mg/日',
    timing: '朝摂取が多い',
    duration: 'ヒトRCTは12週間以内が多く長期データが乏しい',
    sideEffects: ['比較的安全とされるが長期安全データが限られる'],
    contraindications: ['妊娠中・授乳中（データ不足）'],
    products: [
      {
        name: 'NMN 300mg',
        brand: 'Tru Niagen',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 8000,
        dosageMg: 300,
        rank: 1,
        reasonJa: 'Tru Niagenは第三者検査機関による品質保証あり。NMNとNR（ニコチンアミドリボシド）の効果差は現時点で不明だが、Tru Niagenは研究での使用実績が多い',
        highlight: '研究使用実績',
        monthlyCostJpy: 8000,
        note: '現時点ではNR（ニコチンアミドリボシド）と効果差は不明',
      },
    ],
    whoFor: [
      '老化の最先端研究（NAD+・サーチュイン）に関心がある',
      'ヒトデータよりも動物実験の知見を先取りして試したい',
      'ただし「効果が確定した成分」を期待するなら現時点ではS・Aランクを優先すべき',
    ],
    axisScores: { antiAging: 7, skin: 3, cognitive: 4, stress: 2, sleep: 2, immunity: 3, metabolism: 7 },
    emerging: true,
    updatedAt: '2026-04-13',
  },
  {
    slug: 'probiotics',
    nameJa: 'プロバイオティクス',
    nameEn: 'Probiotics',
    evidenceRank: 'A',
    tagline: '腸内環境・免疫機能への関与がRCTで確認されているが菌株特異性に注意',
    description:
      '乳酸菌やビフィズス菌などの生きた微生物。腸内環境の改善、免疫機能のサポートについてRCTでエビデンスがある。ただし「腸活でニキビが治る」など一部の誇大な主張はメタ解析で否定されており、効果は菌株・用途によって大きく異なる。',
    concerns: ['gut', 'immunity'],
    papers: [
      {
        title: 'Probiotics for the prevention of antibiotic-associated diarrhea in children',
        journal: 'Cochrane Database of Systematic Reviews',
        year: 2019,
        studyType: 'meta-analysis',
        sampleSize: 4555,
        keyFinding:
          '抗生物質関連下痢の予防に特定の菌株（LGG・S.boulardii）が有意な効果を示した（RR 0.45）',
      },
      {
        title: 'Probiotics for acne: a systematic review of clinical evidence',
        journal: 'Journal of Dermatological Treatment',
        year: 2021,
        studyType: 'meta-analysis',
        sampleSize: 332,
        keyFinding:
          'ニキビへの効果：炎症性病変数・非炎症性病変数ともにプラセボとの有意差なし（p=0.46〜0.89）',
      },
    ],
    dosageMin: 1000000000,
    dosageMax: 10000000000,
    dosageUnit: 'CFU/日（10億〜100億CFU）',
    timing: '食前または食事と一緒が胃酸の影響を受けにくい',
    duration: '継続的な摂取が必要。摂取をやめると効果が薄れる',
    sideEffects: ['摂取開始時に一時的な腹部膨満感・ガス'],
    contraindications: ['免疫不全状態の方は医師に要相談'],
    products: [
      {
        name: 'Probiotic 50 Billion CFU',
        brand: 'Garden of Life',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 4200,
        rank: 1,
        reasonJa: 'エビデンスのある菌株（LGG・L. acidophilus等）を複数配合。50億CFUは研究で使用された有効量の範囲内。Garden of Lifeは品質管理が厳しい',
        highlight: '菌株実績あり',
        monthlyCostJpy: 4200,
        note: '複数菌株配合。冷蔵保存タイプ',
      },
    ],
    whoFor: [
      '抗生物質を使った後に腸内環境が乱れた',
      '腸の調子が不安定で下痢・便秘を繰り返す',
      '免疫機能を腸から整えたい',
    ],
    axisScores: { antiAging: 3, skin: 2, cognitive: 3, stress: 4, sleep: 3, immunity: 8, metabolism: 4 },
    updatedAt: '2026-04-13',
  },
  {
    slug: 'resveratrol',
    nameJa: 'レスベラトロール',
    nameEn: 'Resveratrol',
    evidenceRank: 'C',
    tagline: '動物実験では有望だが、ヒトでの抗老化効果はまだ確認されていない',
    description:
      'ブドウの皮や赤ワインに含まれるポリフェノール。動物実験でサーチュイン（長寿遺伝子）の活性化・寿命延長が示されているが、ヒトでの大規模RCTはほぼ存在しない。「赤ワインで長生き」の科学的根拠は現時点では不十分。吸収率の低さも課題。',
    concerns: ['inflammation', 'skin-aging'],
    papers: [
      {
        title: 'Resveratrol as an anti-aging therapy: Is the evidence robust?',
        journal: 'Ageing Research Reviews',
        year: 2020,
        studyType: 'observational',
        keyFinding:
          '動物実験での長寿効果・サーチュイン活性化は確認されているが、ヒトRCTでの有意な抗老化効果は現時点で確認されていない',
      },
    ],
    dosageMin: 150,
    dosageMax: 500,
    dosageUnit: 'mg/日',
    timing: '食事と一緒',
    duration: 'ヒトでの最適期間は不明',
    sideEffects: ['高用量で消化器症状', '他のサプリ・薬との相互作用の可能性'],
    contraindications: ['抗凝固薬服用中の方は注意'],
    products: [
      {
        name: 'Resveratrol 200mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 2600,
        dosageMg: 200,
        rank: 1,
        reasonJa: 'レスベラトロールはヒトRCTが少なく「飲むなら低コストで」が原則。NOW Foodsの200mgは価格が適正で、リスクを抑えて試したい場合の選択肢',
        highlight: 'エビデンスC・低コスト優先',
        monthlyCostJpy: 2600,
      },
    ],
    whoFor: [
      'ポリフェノール・サーチュイン研究に興味がある',
      '赤ワインが好きで根拠を知りたい',
      'ただし現時点でのヒトエビデンスはCランク（動物実験が中心）',
    ],
    axisScores: { antiAging: 5, skin: 3, cognitive: 3, stress: 2, sleep: 1, immunity: 4, metabolism: 3 },
    updatedAt: '2026-04-13',
  },

  // ─── スキンケア成分（外用） ────────────────────────────────────────

  {
    slug: 'retinol',
    nameJa: 'レチノール',
    nameEn: 'Retinol',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: '光老化・シワへの改善効果がRCTで繰り返し確認されている外用成分',
    description:
      'レチノールはビタミンAの一形態。皮膚に塗布すると真皮内でレチノイン酸に変換され、コラーゲン産生の促進・ターンオーバーの正常化・メラニン合成の抑制を引き起こす。光老化・シワ・くすみに対する複数のRCTで有意な改善が確認されており、スキンケア成分として最もエビデンスが蓄積されている部類に入る。',
    concerns: ['wrinkles', 'skin-aging', 'uv-damage'],
    papers: [
      {
        title: 'Improvement of naturally aged skin with vitamin A (retinol)',
        journal: 'Archives of Dermatology',
        year: 2007,
        studyType: 'rct',
        sampleSize: 36,
        durationWeeks: 24,
        keyFinding:
          '0.4%レチノール外用でコラーゲン産生の有意な増加と細かいシワの改善を確認（p<0.001）。プラセボ群との差は明確',
      },
      {
        title: 'A comparative study of the effects of retinol and retinoic acid on histological, molecular, and clinical properties of human skin',
        journal: 'Journal of the American Academy of Dermatology',
        year: 2016,
        studyType: 'rct',
        sampleSize: 53,
        durationWeeks: 12,
        keyFinding:
          'レチノール外用でレチノイン酸類似の皮膚改善効果（コラーゲン産生・上皮厚の増加）を低刺激で達成',
      },
    ],
    dosageMin: 0.025,
    dosageMax: 1,
    dosageUnit: '% 濃度',
    timing: '夜のみ使用（光分解するため）。日焼け止め必須',
    duration: '3〜6ヶ月以上の継続使用で効果が現れる。最初の数週間は刺激を感じやすい',
    sideEffects: ['使い始めの赤み・乾燥・皮むけ（レチノイド反応）', '光感受性が高まるため日焼け止め必須'],
    contraindications: ['妊娠中・妊娠希望の方（催奇形性の懸念）', 'ビタミンA誘導体アレルギー'],
    products: [
      {
        name: 'Advanced Retinol + Ferulic 0.2%',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1800,
        rank: 1,
        reasonJa: '初心者は0.2〜0.3%から開始が推奨。フェルラ酸との組み合わせで安定性が高く、レチノイド反応（赤み・皮むけ）が出にくい処方',
        highlight: '初心者向け',
        monthlyCostJpy: 1800,
        note: '初心者向け低濃度。The Ordinaryはエビデンス重視で知られる',
      },
    ],
    whoFor: [
      'シワ・たるみが気になる30代以上',
      '光老化（紫外線ダメージ）のケアをしたい',
      '皮膚科でも推奨される最もエビデンスのある外用成分を使いたい',
    ],
    heroStat: { value: '24週間', label: 'コラーゲン産生増加を確認した研究期間' },
    axisScores: { antiAging: 4, skin: 10, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'retinal',
    nameJa: 'レチナール（レチンアルデヒド）',
    nameEn: 'Retinal / Retinaldehyde',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: 'レチノールより約11倍の変換効率を持つ上位ビタミンA誘導体',
    description:
      'レチナール（レチンアルデヒド）はレチノールとレチノイン酸の中間体。変換ステップが1段階少なく、同濃度でのレチノールより約11倍強い活性を持つとされる。RCTでレチノールと同等かそれ以上の光老化改善効果が確認されており、刺激はレチノイン酸より穏やか。',
    concerns: ['wrinkles', 'skin-aging', 'acne'],
    papers: [
      {
        title: 'Retinaldehyde improves skin aging and photoaging markers in subjects with mild-to-moderate photodamage',
        journal: 'Journal of Cosmetic Dermatology',
        year: 2005,
        studyType: 'rct',
        sampleSize: 125,
        durationWeeks: 18,
        keyFinding:
          '0.05%レチナール外用で光老化スコア（シワ・くすみ・弾力）の有意な改善。トレチノインと類似効果だが刺激が少ない',
      },
      {
        title: 'Comparative study of retinaldehyde vs retinol: clinical efficacy and tolerability',
        journal: 'Skin Pharmacology and Physiology',
        year: 2004,
        studyType: 'rct',
        sampleSize: 64,
        durationWeeks: 16,
        keyFinding:
          'レチナールはレチノールより有意に高い皮膚改善効果を示し、かつ同様の忍容性を維持した',
      },
    ],
    dosageMin: 0.05,
    dosageMax: 0.1,
    dosageUnit: '% 濃度',
    timing: '夜のみ使用。日焼け止め必須',
    duration: '12〜24週間以上の継続使用で効果が現れる',
    sideEffects: ['赤み・乾燥・剥脱（レチノールより強い可能性）'],
    contraindications: ['妊娠中・妊娠希望の方', 'ビタミンA誘導体アレルギー'],
    products: [
      {
        name: 'Granactive Retinoid 2% Emulsion',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1600,
        rank: 1,
        reasonJa: 'レチノールより強い活性を持つレチナール系成分を低刺激エマルジョン処方で配合。レチノールで刺激が出た人やワンランク上の効果を求める人向け',
        highlight: 'レチノールの次のステップ',
        monthlyCostJpy: 1600,
        note: 'レチノイドエステル配合の低刺激処方',
      },
    ],
    whoFor: [
      'レチノールを使っていて物足りなくなった',
      '刺激が強すぎるレチノイン酸の代替を探している',
      'より速く効果を出したい・レチノールの上位互換を試したい',
    ],
    axisScores: { antiAging: 4, skin: 9, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'vitamin-c-topical',
    nameJa: 'ビタミンC誘導体（外用）',
    nameEn: 'Topical Vitamin C (L-Ascorbic Acid)',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: 'コラーゲン合成促進・美白・抗酸化がRCTで確認されている外用成分',
    description:
      '外用ビタミンC（L-アスコルビン酸およびその誘導体）は、コラーゲン合成の促進、メラニン産生の抑制、UV誘発酸化ストレスの軽減において複数のRCTで有効性が示されている。安定性が低いため、誘導体（アスコルビルグルコシド・3-O-エチルアスコルビン酸等）や安定化処方（フェルラ酸との組み合わせ）が有効。',
    concerns: ['skin-aging', 'spots', 'uv-damage'],
    papers: [
      {
        title: 'Topical Vitamin C: A Useful Agent for Treating Photoaging and Other Dermatologic Conditions',
        journal: 'Dermatologic Surgery',
        year: 2005,
        studyType: 'rct',
        sampleSize: 60,
        durationWeeks: 12,
        keyFinding:
          '10〜20% L-アスコルビン酸外用でシミ・光老化スコアの有意な改善。皮膚コラーゲン産生の増加も確認',
      },
      {
        title: 'Ferulic acid stabilizes a solution of vitamins C and E and doubles its photoprotection of skin',
        journal: 'Journal of Investigative Dermatology',
        year: 2005,
        studyType: 'rct',
        sampleSize: 10,
        durationWeeks: 4,
        keyFinding:
          'フェルラ酸との組み合わせ（CE-Ferulic処方）でビタミンCの安定性と光保護効果が2倍に向上',
      },
    ],
    dosageMin: 10,
    dosageMax: 20,
    dosageUnit: '% 濃度',
    timing: '朝使用が最も効果的（光保護効果のため）。日焼け止めと重ねる',
    duration: '8〜12週間で色素改善効果が現れる研究が多い',
    sideEffects: ['高濃度（20%以上）で刺激・赤み', '酸化で変色・効果低下しやすい'],
    contraindications: ['敏感肌の方は低濃度（5〜10%）から開始推奨'],
    products: [
      {
        name: 'Vitamin C Suspension 23% + HA Spheres 2%',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1500,
        rank: 1,
        reasonJa: '23%という高濃度でRCTに近い条件を達成できるが刺激が強い。敏感肌は10%処方（Ascorbyl Glucoside Solution 12%等）から始めることを推奨',
        highlight: '高濃度・刺激注意',
        monthlyCostJpy: 1500,
        note: '高濃度だが刺激が強い。敏感肌は10%処方を推奨',
      },
    ],
    whoFor: [
      'シミ・くすみを朝のスキンケアで改善したい',
      'コラーゲン合成を皮膚の外側からサポートしたい',
      'UV後の酸化ダメージを日焼け止めに加えてケアしたい',
    ],
    axisScores: { antiAging: 4, skin: 9, cognitive: 0, stress: 0, sleep: 0, immunity: 3, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'ceramide',
    nameJa: 'セラミド',
    nameEn: 'Ceramide',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: '皮膚バリア機能の修復・水分保持への関与がRCTで確認されている',
    description:
      'セラミドは皮膚の角質細胞間脂質の主成分（約50%）で、水分の蒸散を防ぎバリア機能を維持する。アトピー性皮膚炎ではセラミドが減少することが確認されており、外用セラミドによる補充でバリア機能の改善・経皮水分蒸散量（TEWL）の低下が複数のRCTで示されている。',
    concerns: ['dry-skin', 'barrier', 'skin-aging'],
    papers: [
      {
        title: 'Emollient enhancement of the skin barrier from birth offers effective atopic dermatitis prevention',
        journal: 'Journal of Allergy and Clinical Immunology',
        year: 2014,
        studyType: 'rct',
        sampleSize: 124,
        durationWeeks: 32,
        keyFinding:
          '出生直後からの保湿剤（セラミド含有）使用でアトピー性皮膚炎の発症リスクが50%低下（p=0.017）',
      },
      {
        title: 'A multicenter randomized trial of a ceramide-containing emollient in the management of atopic dermatitis',
        journal: 'Journal of the American Academy of Dermatology',
        year: 2016,
        studyType: 'rct',
        sampleSize: 169,
        durationWeeks: 8,
        keyFinding:
          'セラミド配合エモリエントがTEWL・かゆみ・湿疹スコアを有意に改善。プラセボとの差が明確',
      },
    ],
    dosageMin: 1,
    dosageMax: 3,
    dosageUnit: '% 濃度',
    timing: '朝晩の洗顔後に使用。乳液・クリームタイプが保水力高い',
    duration: '継続使用で効果を維持。使用中止で効果は薄れる',
    sideEffects: ['基本的に刺激が少なく安全性が高い'],
    contraindications: ['セラミドアレルギー（稀）'],
    products: [
      {
        name: 'Moisturizing Cream',
        brand: 'CeraVe',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1800,
        rank: 1,
        reasonJa: 'セラミド1・3・6-IIの3種類を配合し、皮膚の天然バリアに近い組成を再現。皮膚科医が最も推薦するセラミドブランドの一つで価格も手頃',
        highlight: '皮膚科医推奨',
        monthlyCostJpy: 1800,
        note: '3種類のセラミド + ヒアルロン酸配合。皮膚科医推奨ブランド',
      },
    ],
    whoFor: [
      '乾燥肌・アトピー傾向があり肌のバリアが弱い',
      '肌荒れが繰り返す・刺激に弱い肌',
      'スキンケアの土台（保湿・バリア）から整えたい',
    ],
    axisScores: { antiAging: 2, skin: 7, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'bakuchiol',
    nameJa: 'バクチオール',
    nameEn: 'Bakuchiol',
    evidenceRank: 'B',
    usageType: 'topical',
    tagline: 'レチノールと類似の光老化改善が示されているが研究数はまだ少ない',
    description:
      'バクチオールはアーユルヴェーダに由来する植物由来成分。レチノールと同様の遺伝子発現変化（コラーゲン産生促進・MMP抑制）を引き起こすことが確認されており、レチノールとの直接比較RCTでほぼ同等の光老化改善効果が示されている。ただし研究数は少なく、様々な濃度での最適化も途上。',
    concerns: ['wrinkles', 'skin-aging'],
    papers: [
      {
        title: 'Prospective, randomized, double-blind assessment of topical bakuchiol and retinol for facial photoageing',
        journal: 'British Journal of Dermatology',
        year: 2019,
        studyType: 'rct',
        sampleSize: 44,
        durationWeeks: 12,
        keyFinding:
          '0.5%バクチオール（2回/日）と0.5%レチノール（1回/日）を比較。シワ・色素の改善度に有意差なし。バクチオールは刺激が有意に少なかった',
      },
    ],
    dosageMin: 0.5,
    dosageMax: 1,
    dosageUnit: '% 濃度',
    timing: '朝晩使用可能（光感受性が低い）。妊娠中にも使いやすいレチノール代替として注目',
    duration: '12週間以上の継続で効果が現れる',
    sideEffects: ['基本的に刺激が少ない。レチノールより忍容性が高い'],
    contraindications: ['バクチオールアレルギー（非常に稀）'],
    products: [
      {
        name: '100% Plant-Derived Squalane + Phyto-Retinol Serum',
        brand: 'Biossance',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 4800,
        rank: 1,
        reasonJa: 'バクチオール＋スクワランの組み合わせは保湿しながらレチノール代替ケアが可能。妊娠中・レチノール刺激が気になる方に最適な選択肢',
        highlight: '妊娠中も使える',
        monthlyCostJpy: 4800,
        note: 'バクチオール + スクワランの組み合わせ。妊娠中にも使いやすい',
      },
    ],
    whoFor: [
      '妊娠中・妊娠希望でレチノールが使えない',
      'レチノールで赤みや皮むけが出た',
      '刺激の少ないレチノール代替を朝晩使いたい',
    ],
    axisScores: { antiAging: 3, skin: 8, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'glycolic-acid',
    nameJa: 'グリコール酸（AHA）',
    nameEn: 'Glycolic Acid (AHA)',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: '角質ターンオーバー促進・毛穴・色素改善がRCTで確認されている',
    description:
      'グリコール酸はAHA（α-ヒドロキシ酸）の一種で、最も分子量が小さく角質層への浸透性が高い。細胞接着を弱めることで角質を除去し、肌のテクスチャー改善・色素沈着の軽減・細かいシワへの効果がRCTで確認されている。濃度と使用法によってはサロンケア〜ホームケアまで幅広く使用される。',
    concerns: ['pores', 'spots', 'skin-aging', 'acne'],
    papers: [
      {
        title: 'Long-term efficacy and safety of glycolic acid peels for the treatment of facial melasma',
        journal: 'Journal of Cosmetic Dermatology',
        year: 2019,
        studyType: 'rct',
        sampleSize: 60,
        durationWeeks: 12,
        keyFinding:
          '35%グリコール酸ピールを4週おきに3回施術でMASIスコア（肝斑）が有意に低下（p<0.001）',
      },
      {
        title: 'Glycolic acid in the treatment of photoaging: a randomized controlled trial',
        journal: 'Dermatologic Surgery',
        year: 2001,
        studyType: 'rct',
        sampleSize: 40,
        durationWeeks: 22,
        keyFinding:
          '8%グリコール酸ローション長期使用でケラトーシス・くすみ・細かいシワの有意な改善',
      },
    ],
    dosageMin: 5,
    dosageMax: 10,
    dosageUnit: '% 濃度',
    timing: '夜使用推奨。使用後は日焼け止め必須（光感受性増加）',
    duration: '6〜12週間で肌のテクスチャー改善が現れる研究が多い',
    sideEffects: ['ピリつき・赤み・乾燥（特に高濃度）', '光感受性の増加'],
    contraindications: ['活動性の湿疹・傷のある肌への使用不可', '高濃度製品はプロフェッショナルによる施術推奨'],
    products: [
      {
        name: 'Glycolic Acid 7% Toning Solution',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1300,
        rank: 1,
        reasonJa: '7%はホームケアに適した安全濃度。週2〜3回の使用で角質ターンオーバーを促進。The Ordinaryのグリコール酸は最もコスパが高いAHA製品の一つ',
        highlight: 'コスパ最強',
        monthlyCostJpy: 1300,
        note: '7%濃度でホームケアに適した濃度。週2〜3回から開始',
      },
    ],
    whoFor: [
      '角質肥厚・毛穴詰まりが気になる',
      '肌のトーンが均一でなくくすみが気になる',
      'ターンオーバーを促進して透明感を出したい',
    ],
    axisScores: { antiAging: 2, skin: 7, cognitive: 0, stress: 0, sleep: 0, immunity: 1, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'salicylic-acid',
    nameJa: 'サリチル酸（BHA）',
    nameEn: 'Salicylic Acid (BHA)',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: 'ニキビ・毛穴詰まりへの改善効果がRCTで繰り返し確認されている',
    description:
      'サリチル酸はBHA（β-ヒドロキシ酸）の代表。脂溶性のため毛穴の皮脂に浸透しやすく、角栓の溶解・毛穴の黒ずみ・ニキビ（尋常性ざ瘡）への効果が複数のRCTで確認されている。抗炎症作用も持ち、赤ニキビにも効果的。',
    concerns: ['acne', 'pores'],
    papers: [
      {
        title: 'A double-blind randomized trial of 2% salicylic acid vs benzoyl peroxide for acne vulgaris',
        journal: 'Cutis',
        year: 2004,
        studyType: 'rct',
        sampleSize: 60,
        durationWeeks: 8,
        keyFinding:
          '2%サリチル酸で面疱（白ニキビ・黒ニキビ）数が有意に減少。過酸化ベンゾイルと同等の効果',
      },
      {
        title: 'Efficacy of topical salicylic acid with photoprotection for melasma management',
        journal: 'Journal of Cosmetic Dermatology',
        year: 2018,
        studyType: 'rct',
        sampleSize: 50,
        durationWeeks: 12,
        keyFinding:
          '30%サリチル酸ピール（月1回3回施術）でMASIスコアの有意な低下と肌テクスチャーの改善',
      },
    ],
    dosageMin: 0.5,
    dosageMax: 2,
    dosageUnit: '% 濃度',
    timing: '夜使用が多い。使用後は日焼け止め推奨',
    duration: '4〜8週間でニキビ・毛穴の改善が現れる研究が多い',
    sideEffects: ['乾燥・ピリつき', '過剰使用で皮脂を取りすぎる'],
    contraindications: ['アスピリンアレルギーの方（同系の化合物）', '傷のある肌への使用不可'],
    products: [
      {
        name: 'Salicylic Acid 2% Anhydrous Solution',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1200,
        rank: 1,
        reasonJa: 'RCTで使用された2%濃度をそのまま達成。脂溶性で毛穴に浸透しやすく、ニキビの黒ずみ・白ニキビ両方に対応。スポット使用も全顔使用も可能',
        highlight: 'ニキビに最短距離',
        monthlyCostJpy: 1200,
        note: '2%濃度。ニキビ・毛穴ケアのスポット使用にも',
      },
    ],
    whoFor: [
      'ニキビ・毛穴の黒ずみが繰り返す',
      '皮脂分泌が多いオイリー肌',
      '炎症性の赤ニキビにも対応したい',
    ],
    axisScores: { antiAging: 1, skin: 6, cognitive: 0, stress: 0, sleep: 0, immunity: 2, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'azelaic-acid',
    nameJa: 'アゼライン酸',
    nameEn: 'Azelaic Acid',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: '色素沈着・ニキビ・酒さへの効果がRCTで確認されている多機能成分',
    description:
      'アゼライン酸は穀物由来のジカルボン酸。チロシナーゼ（メラニン合成酵素）の阻害・抗炎症・殺菌（ニキビの原因菌P.acnesへの作用）という3つの作用を持つ。色素沈着・ニキビ・酒さ（ロザシア）への効果が複数のRCTで確認されており、欧米では医薬品としても承認されている。',
    concerns: ['spots', 'acne', 'skin-aging'],
    papers: [
      {
        title: 'Azelaic acid 15% gel in the treatment of papulopustular rosacea: a randomized, double-blind, vehicle-controlled study',
        journal: 'Archives of Dermatology',
        year: 2006,
        studyType: 'rct',
        sampleSize: 251,
        durationWeeks: 12,
        keyFinding:
          'アゼライン酸15%ゲルで酒さの炎症性病変数が有意に減少（p<0.001）。FDA承認の根拠となった試験',
      },
      {
        title: 'Comparative study of azelaic acid 20% cream versus hydroquinone 4% cream in treatment of melasma',
        journal: 'Journal of Dermatological Treatment',
        year: 2020,
        studyType: 'rct',
        sampleSize: 40,
        durationWeeks: 24,
        keyFinding:
          '20%アゼライン酸が4%ハイドロキノンと同等の肝斑改善効果を示した。かつ安全性プロファイルが優秀',
      },
    ],
    dosageMin: 10,
    dosageMax: 20,
    dosageUnit: '% 濃度',
    timing: '朝晩使用可能。日焼け止めとの併用推奨',
    duration: '12〜24週間の継続で色素・ニキビ改善効果が現れる',
    sideEffects: ['使い始めのピリつき・軽い赤み（通常は数週間で慣れる）'],
    contraindications: ['アゼライン酸アレルギー（非常に稀）'],
    products: [
      {
        name: 'Azelaic Acid Suspension 10%',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1400,
        rank: 1,
        reasonJa: '10%はホームケアで使える最高濃度。処方箋なしで入手でき、シミ・ニキビ・酒さに1本でアプローチできる。敏感肌でも比較的使いやすい',
        highlight: '多機能・低刺激',
        monthlyCostJpy: 1400,
        note: '10%濃度のホームケア処方。処方箋不要で入手可能',
      },
    ],
    whoFor: [
      'シミとニキビを同時にケアしたい',
      '酒さ（ロザシア）の赤みが気になる',
      'ハイドロキノンは刺激が強すぎた・処方箋なしで使える美白成分を探している',
    ],
    axisScores: { antiAging: 2, skin: 7, cognitive: 0, stress: 0, sleep: 0, immunity: 3, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'hyaluronic-acid',
    nameJa: 'ヒアルロン酸（外用）',
    nameEn: 'Hyaluronic Acid (Topical)',
    evidenceRank: 'B',
    usageType: 'topical',
    tagline: '表皮の水分保持に働くが、真皮への浸透は分子量に依存する',
    description:
      '外用ヒアルロン酸は皮膚表面の水分保持を助ける。しかし高分子HA（>1MDa）は角質層を通過できず、保湿効果は表皮レベルに留まる。低分子HA（<50kDa）は真皮への浸透が示唆されているが、ヒトRCTでの長期効果確認はまだ限定的。総合的なエビデンスは「保湿の観点では有効だが、抗老化効果としてはエビデンスが不十分」。',
    concerns: ['dry-skin', 'skin-aging'],
    papers: [
      {
        title: 'Efficacy of a New Topical Nano-hyaluronic Acid in Humans',
        journal: 'Journal of Clinical and Aesthetic Dermatology',
        year: 2011,
        studyType: 'rct',
        sampleSize: 76,
        durationWeeks: 8,
        keyFinding:
          'ナノHA（低分子）外用で皮膚水分量と弾力が有意に改善。高分子HAとの比較では低分子が優れた結果',
      },
    ],
    dosageMin: 0.1,
    dosageMax: 2,
    dosageUnit: '% 濃度',
    timing: '洗顔後の濡れた肌に塗布すると保湿効果が高まる',
    duration: '継続使用で保湿効果を維持。使用中止で効果は低下する',
    sideEffects: ['基本的に安全性が高く刺激少ない'],
    contraindications: ['HAアレルギー（非常に稀）'],
    products: [
      {
        name: 'Hyaluronic Acid 2% + B5',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1400,
        rank: 1,
        reasonJa: '高分子・低分子・超低分子の3種類のHAを配合し、表皮から深層まで段階的に保湿。パンテノール（B5）との組み合わせで刺激が少なく、他の成分（レチノールなど）と重ねやすい',
        highlight: '重ね使いの土台',
        monthlyCostJpy: 1400,
        note: '複数分子量のHAを配合。パンテノール（B5）で刺激を和らげる処方',
      },
    ],
    whoFor: [
      '乾燥による小じわ・突っ張り感が気になる',
      'スキンケアのベース保湿が不十分だと感じる',
      'レチノールなど他の成分の刺激を和らげたい',
    ],
    axisScores: { antiAging: 2, skin: 7, cognitive: 0, stress: 0, sleep: 0, immunity: 1, metabolism: 0 },
    updatedAt: '2026-04-13',
  },

  // ─── 経口成分（追加） ────────────────────────────────────────

  {
    slug: 'vitamin-c-oral',
    nameJa: 'ビタミンC（経口）',
    nameEn: 'Vitamin C (Oral)',
    evidenceRank: 'S',
    usageType: 'oral',
    tagline: '免疫機能・皮膚コラーゲン合成・抗酸化への関与がメタ解析で確認されている',
    description:
      'ビタミンC（L-アスコルビン酸）は水溶性ビタミンで、ヒトは体内合成できないため食事・サプリから摂取する必要がある。免疫細胞の機能維持、コラーゲン合成に必須の補酵素、活性酸素（ROS）の除去という3つの役割が確立されている。欠乏すると壊血病が生じるほど根拠が明確な成分。',
    concerns: ['immunity', 'skin-aging', 'inflammation'],
    papers: [
      {
        title: 'Vitamin C and Immune Function',
        journal: 'Nutrients',
        year: 2017,
        studyType: 'meta-analysis',
        sampleSize: 12000,
        keyFinding:
          '免疫細胞の機能維持・活性化酸素除去・抗感染効果をサポートすることがメタ解析・RCT群で確認',
      },
      {
        title: 'Vitamin C for preventing and treating the common cold',
        journal: 'Cochrane Database of Systematic Reviews',
        year: 2013,
        studyType: 'meta-analysis',
        sampleSize: 11306,
        keyFinding:
          '1g/日以上の継続摂取で風邪の罹患期間を約8%短縮（成人）〜14%短縮（小児）。予防効果は一般集団では限定的だが高強度運動実施者では有意',
      },
    ],
    dosageMin: 500,
    dosageMax: 1000,
    dosageUnit: 'mg/日',
    timing: '食事と一緒が消化器症状を減らす。1日2〜3回に分けると吸収率が高まる',
    duration: '欠乏しないように継続的な摂取が重要',
    sideEffects: ['高用量（2g以上）で下痢・消化器症状', '腎結石リスクが一部研究で示唆（高用量長期）'],
    contraindications: ['腎結石の既往がある方は高用量を避ける'],
    products: [
      {
        name: 'Vitamin C 1000mg with Bioflavonoids',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1800,
        dosageMg: 1000,
        rank: 1,
        reasonJa: '1gはRCTで最も多く使用された用量。バイオフラボノイドとの組み合わせで吸収率が向上。NOW Foodsは圧倒的なコスパで月1,800円以下で摂取できる',
        highlight: 'コスパ最強',
        monthlyCostJpy: 1800,
        note: 'バイオフラボノイド配合で吸収率向上。コスパ重視',
      },
    ],
    whoFor: [
      '免疫機能をサポートしたい',
      '野菜・果物の摂取が少なくビタミンCが不足しがち',
      'コラーゲン合成を内側からサポートしたい',
    ],
    heroStat: { value: '11,306名', label: 'Cochraneメタ解析のエビデンス規模' },
    axisScores: { antiAging: 6, skin: 5, cognitive: 4, stress: 3, sleep: 1, immunity: 8, metabolism: 3 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'zinc',
    nameJa: '亜鉛',
    nameEn: 'Zinc',
    evidenceRank: 'A',
    usageType: 'oral',
    tagline: 'ニキビ・皮膚の修復・免疫機能への関与がRCTで確認されている',
    description:
      '亜鉛は200以上の酵素の補助因子。皮膚の修復（創傷治癒）・ニキビ（炎症性座瘡）の軽減・免疫応答の調整への関与がRCTで確認されている。日本人の食事では不足しやすいミネラルの一つ。過剰摂取は銅の吸収を阻害するため注意が必要。',
    concerns: ['acne', 'immunity', 'skin-aging'],
    papers: [
      {
        title: 'Zinc supplementation in the treatment of acne vulgaris: a systematic review and meta-analysis',
        journal: 'Dermatology',
        year: 2020,
        studyType: 'meta-analysis',
        sampleSize: 1024,
        durationWeeks: 12,
        keyFinding:
          '亜鉛経口補給でニキビスコアが有意に改善。抗生物質よりは効果が劣るが副作用プロファイルが優秀',
      },
      {
        title: 'Zinc in Human Health: Effect of Zinc on Immune Cells',
        journal: 'Molecular Medicine',
        year: 2008,
        studyType: 'cohort',
        sampleSize: 3000,
        keyFinding:
          '亜鉛欠乏でT細胞機能・自然免疫が低下することが確認。補充で免疫機能が回復',
      },
    ],
    dosageMin: 25,
    dosageMax: 40,
    dosageUnit: 'mg/日',
    timing: '食後（空腹時は消化器症状が出やすい）',
    duration: '8〜12週間の継続で効果を確認した研究が多い',
    sideEffects: ['高用量（50mg以上）で嘔気・銅欠乏リスク', '空腹時摂取で消化器刺激'],
    contraindications: ['銅欠乏の方（亜鉛過剰で悪化）'],
    products: [
      {
        name: 'Zinc Picolinate 50mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1600,
        dosageMg: 50,
        rank: 1,
        reasonJa: 'ピコリン酸亜鉛は吸収率が高い形態の一つ。50mgは上限量だが食事からの摂取が多い場合は25mgに減量を。銅との拮抗作用に注意',
        highlight: '吸収率重視',
        monthlyCostJpy: 1600,
        note: 'ピコリン酸亜鉛は吸収率が高い形態。25〜50mgで使用',
      },
    ],
    whoFor: [
      'ニキビが繰り返しできる',
      '傷の治りが遅いと感じる',
      '免疫機能の底上げとスキンケアを同時にしたい',
    ],
    axisScores: { antiAging: 4, skin: 5, cognitive: 4, stress: 3, sleep: 2, immunity: 8, metabolism: 4 },
    updatedAt: '2026-04-13',
  },

  {
    slug: 'biotin',
    nameJa: 'ビオチン',
    nameEn: 'Biotin',
    evidenceRank: 'C',
    usageType: 'oral',
    tagline: '欠乏者への効果は確実だが、通常食の人への「美容効果」は論文で否定されている',
    description:
      'ビオチン（ビタミンB7）は脂肪酸合成・アミノ酸代謝に関わる水溶性ビタミン。欠乏すると脱毛・皮膚炎・爪の変形が起きる。しかし日本人の通常の食生活では欠乏はまれであり、「ビオチンを飲めば髪が増える・爪が強くなる」という主張を支持するヒトRCTは現時点でほぼ存在しない。ビオチンの美容サプリは最も過大評価されている成分の一つ。',
    concerns: ['hair'],
    papers: [
      {
        title: 'A Review of the Use of Biotin for Hair Loss',
        journal: 'Skin Appendage Disorders',
        year: 2017,
        studyType: 'observational',
        keyFinding:
          'ビオチンによる発毛効果を示したケースレポートは全て欠乏状態または基礎疾患のある患者。健常者での対照試験（RCT）は現時点で存在しない',
      },
    ],
    dosageMin: 30,
    dosageMax: 100,
    dosageUnit: 'μg/日',
    timing: '食事と一緒',
    duration: '通常食で欠乏はほぼないため、追加摂取の根拠は薄い',
    sideEffects: ['高用量（数mg以上）で甲状腺・ホルモン検査の偽陽性を引き起こす可能性'],
    contraindications: ['甲状腺・ホルモン検査を控えている方は検査前に摂取中止を'],
    products: [],
    whoFor: [
      '通常の食生活を送っている場合は追加摂取の必要はほぼない',
      'ビオチン欠乏症（摂食障害・特定の薬剤服用）が疑われる方のみ',
      '「飲めば髪が増える」という主張はRCTで支持されていない',
    ],
    axisScores: { antiAging: 1, skin: 3, cognitive: 0, stress: 0, sleep: 0, immunity: 1, metabolism: 2 },
    updatedAt: '2026-04-13',
  },

  // ─── 睡眠・リラックス成分 ────────────────────────────────────────

  {
    slug: 'l-theanine',
    nameJa: 'L-テアニン',
    nameEn: 'L-Theanine',
    evidenceRank: 'A',
    usageType: 'oral',
    tagline: 'リラックス・ストレス軽減・睡眠の質への関与がRCTで確認されている',
    description:
      'L-テアニンは緑茶に含まれるアミノ酸。α波の増加（覚醒時のリラックス状態）・コルチゾール応答の抑制・睡眠の質改善への関与がRCTで確認されている。カフェインと組み合わせることで集中力向上と不安軽減を同時に引き起こす効果も複数の研究で示されており、安全性プロファイルが非常に高い。',
    concerns: ['stress', 'sleep', 'cognitive'],
    papers: [
      {
        title: 'The effects of L-theanine on cognitive performance: a systematic review and meta-analysis',
        journal: 'Nutritional Neuroscience',
        year: 2021,
        studyType: 'meta-analysis',
        sampleSize: 380,
        durationWeeks: 4,
        keyFinding:
          'L-テアニン（単独またはカフェインとの組み合わせ）が注意・記憶・反応速度を有意に改善。ストレス応答の軽減も確認',
      },
      {
        title: 'L-Theanine reduces psychological and physiological stress responses',
        journal: 'Biological Psychology',
        year: 2007,
        studyType: 'rct',
        sampleSize: 12,
        durationWeeks: 1,
        keyFinding:
          '急性ストレス負荷時の心拍変動・唾液コルチゾールをL-テアニン摂取群でプラセボ比で有意に抑制',
      },
    ],
    dosageMin: 100,
    dosageMax: 400,
    dosageUnit: 'mg/日',
    timing: 'ストレス・集中目的は朝〜日中。睡眠目的は就寝30〜60分前',
    duration: '急性効果（単回摂取）から確認されている。継続摂取で睡眠改善効果が現れる',
    sideEffects: ['基本的に安全性が高く副作用報告は少ない', 'まれに頭痛・消化器症状'],
    contraindications: ['降圧薬服用中の方は注意（血圧低下作用の可能性）'],
    products: [
      {
        name: 'L-Theanine 200mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1800,
        dosageMg: 200,
        rank: 1,
        reasonJa: '論文使用量100〜200mgを1カプセルで達成。NOW Foodsは品質管理が確立されておりコスパが高い',
        highlight: 'コスパ最強',
        monthlyCostJpy: 1800,
      },
    ],
    heroStat: { value: '380名', label: 'ストレス・認知改善メタ解析の規模' },
    axisScores: { antiAging: 2, skin: 0, cognitive: 7, stress: 8, sleep: 7, immunity: 2, metabolism: 2 },
    updatedAt: '2026-04-15',
  },

  {
    slug: 'glycine',
    nameJa: 'グリシン',
    nameEn: 'Glycine',
    evidenceRank: 'A',
    usageType: 'oral',
    tagline: '睡眠の質・深睡眠の増加がRCTで確認されているアミノ酸',
    description:
      'グリシンは最小のアミノ酸で、コラーゲン（全アミノ酸の約1/3をグリシンが占める）や抑制性神経伝達物質として機能する。就寝前の摂取で深部体温の低下を促し、深睡眠（徐波睡眠）の増加と翌朝の疲労感軽減がRCTで確認されている。サプリメントとして最もエビデンスの高い睡眠改善成分の一つ。',
    concerns: ['sleep', 'fatigue', 'skin-aging'],
    papers: [
      {
        title: 'Glycine ingestion improves subjective sleep quality in human volunteers',
        journal: 'Sleep and Biological Rhythms',
        year: 2007,
        studyType: 'rct',
        sampleSize: 19,
        durationWeeks: 1,
        keyFinding:
          '就寝前3gのグリシン摂取で翌朝の疲労感・眠気が有意に改善。主観的睡眠の質スコアが向上',
      },
      {
        title: 'Glycine improves the quality of sleep in a dose-dependent fashion',
        journal: 'Frontiers in Neurology',
        year: 2019,
        studyType: 'rct',
        sampleSize: 40,
        durationWeeks: 4,
        keyFinding:
          'グリシン3g/日の継続摂取で睡眠効率・深睡眠比率が有意に改善。深部体温の低下との相関が確認',
      },
    ],
    dosageMin: 3000,
    dosageMax: 5000,
    dosageUnit: 'mg/日',
    timing: '就寝30〜60分前に摂取。粉末タイプをお湯に溶かすと飲みやすい',
    duration: '継続摂取で効果を維持。1週間以内から効果を感じる報告もある',
    sideEffects: ['基本的に安全性が高い。高用量で消化器症状（まれ）'],
    contraindications: ['特になし。腎機能低下のある方は高用量を避ける'],
    products: [
      {
        name: 'Glycine 1000mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1600,
        dosageMg: 1000,
        rank: 1,
        reasonJa: '論文使用量3gを3カプセルで達成。純度が高く価格も適正。粉末タイプより持ち運びやすい',
        highlight: '睡眠特化',
        monthlyCostJpy: 1600,
      },
    ],
    heroStat: { value: '3g', label: '睡眠改善に必要な1日量（RCT）' },
    axisScores: { antiAging: 3, skin: 3, cognitive: 2, stress: 4, sleep: 9, immunity: 2, metabolism: 3 },
    updatedAt: '2026-04-15',
  },

  {
    slug: 'creatine',
    nameJa: 'クレアチン',
    nameEn: 'Creatine',
    evidenceRank: 'S',
    usageType: 'oral',
    tagline: '筋力・筋量・認知機能への関与がメタ解析で繰り返し確認されている',
    description:
      'クレアチンはリン酸クレアチンとしてATP再合成に関わるエネルギー代謝物質。サプリメント中で最もエビデンスが蓄積されており、筋力・無酸素運動パフォーマンスへの効果がメタ解析で確定的に示されている。近年では認知機能（特に睡眠不足時・加齢による低下）への改善効果も複数のRCTで報告されている。',
    concerns: ['fatigue', 'cognitive'],
    papers: [
      {
        title: 'Creatine supplementation and exercise performance: a systematic review',
        journal: 'Journal of Strength and Conditioning Research',
        year: 2020,
        studyType: 'meta-analysis',
        sampleSize: 22000,
        durationWeeks: 12,
        keyFinding:
          '筋力・除脂肪体重・無酸素運動パフォーマンスへの有意な効果がメタ解析で確定的に示された（100以上のRCT統合）',
      },
      {
        title: 'Creatine supplementation improves cognitive performance in healthy adults',
        journal: 'Experimental Gerontology',
        year: 2022,
        studyType: 'meta-analysis',
        sampleSize: 750,
        durationWeeks: 8,
        keyFinding:
          '記憶・処理速度への改善効果が確認。特に高齢者・睡眠不足状態での認知への効果が顕著（p<0.05）',
      },
    ],
    dosageMin: 3000,
    dosageMax: 5000,
    dosageUnit: 'mg/日',
    timing: 'タイミングは問わない。毎日同じ時間に継続摂取が重要',
    duration: '4週間以上の継続で筋力・認知への効果が現れる。ローディングは必須ではない',
    sideEffects: ['水分貯留による体重増加（1〜2kg、主に筋肉内）', '高用量で消化器症状（分割摂取で軽減）'],
    contraindications: ['腎機能低下のある方は医師に要相談（排泄負荷のため）'],
    products: [
      {
        name: 'Creatine Monohydrate Powder 1kg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 2200,
        dosageMg: 5000,
        rank: 1,
        reasonJa: 'クレアチンモノハイドレートは最もエビデンスが多い形態。他の形態（HCl等）との優位差なし。1kgで約200回分のコスパ',
        highlight: 'コスパ最強',
        monthlyCostJpy: 2200,
      },
    ],
    heroStat: { value: '100件以上', label: 'RCTが支持する筋力・認知効果' },
    axisScores: { antiAging: 4, skin: 0, cognitive: 7, stress: 3, sleep: 3, immunity: 3, metabolism: 9 },
    updatedAt: '2026-04-15',
  },

  {
    slug: 'melatonin',
    nameJa: 'メラトニン',
    nameEn: 'Melatonin',
    evidenceRank: 'S',
    usageType: 'oral',
    tagline: '入眠時間短縮・時差ぼけへの効果がメタ解析で確認されている',
    description:
      'メラトニンは松果体から分泌される「暗闇のホルモン」。概日リズムの調節を担い、入眠のシグナルとなる。入眠時間の短縮・時差ぼけの改善・概日リズム障害への効果がメタ解析で確認されている。日本では医薬品扱い（要処方）のため、iHerbなど海外サプリサイトからの個人輸入が必要。低用量（0.5〜1mg）から始めることが推奨されている。',
    concerns: ['sleep'],
    papers: [
      {
        title: 'Melatonin for the prevention and treatment of jet lag (Cochrane Review)',
        journal: 'Cochrane Database of Systematic Reviews',
        year: 2002,
        studyType: 'meta-analysis',
        sampleSize: 1200,
        keyFinding:
          '時差ぼけの予防・治療に0.5〜5mgのメラトニンが有効。タイムゾーンを5つ以上越える渡航で特に効果的',
      },
      {
        title: 'Meta-analysis: melatonin for the treatment of primary sleep disorders',
        journal: 'PLOS ONE',
        year: 2013,
        studyType: 'meta-analysis',
        sampleSize: 1683,
        durationWeeks: 4,
        keyFinding:
          '入眠潜時を平均7.06分短縮（p<0.001）。睡眠効率・総睡眠時間も有意に改善',
      },
    ],
    dosageMin: 0.5,
    dosageMax: 5,
    dosageUnit: 'mg/日',
    timing: '就寝30〜60分前に低用量（0.5〜1mg）から開始。高用量は翌朝のだるさにつながる可能性',
    duration: '時差ぼけ：渡航前後数日。慢性的な入眠困難：継続摂取が必要だが依存性は低い',
    sideEffects: ['翌朝の眠気（高用量で増加）', 'まれに頭痛・めまい'],
    contraindications: ['日本では医薬品（要処方）のため個人輸入が必要', '妊娠中・授乳中（データ不足）', '自己免疫疾患のある方'],
    products: [
      {
        name: 'Melatonin 1mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 1400,
        dosageMg: 1,
        rank: 1,
        reasonJa: '低用量1mgから開始が推奨。高用量（5〜10mg）は翌朝のだるさリスクが高く、効果は低用量と同等の研究が多い',
        highlight: '低用量推奨',
        monthlyCostJpy: 1400,
      },
    ],
    heroStat: { value: '7分短縮', label: '入眠潜時の平均短縮（メタ解析）' },
    axisScores: { antiAging: 3, skin: 1, cognitive: 2, stress: 3, sleep: 10, immunity: 3, metabolism: 2 },
    updatedAt: '2026-04-15',
  },

  {
    slug: 'gaba',
    nameJa: 'GABA',
    nameEn: 'GABA (Gamma-Aminobutyric Acid)',
    evidenceRank: 'B',
    usageType: 'oral',
    tagline: 'ストレス軽減・睡眠改善の効果がRCTで示されているが機序に議論あり',
    description:
      'GABAは中枢神経系の主要な抑制性神経伝達物質。経口摂取したGABAが血液脳関門を通過するかは議論が続いているが、腸管でのGABA受容体への作用・迷走神経を介した間接経路が示唆されており、複数のRCTでストレス軽減・睡眠改善の効果が確認されている。エビデンスは「効果はある、機序は不明」の状態。',
    concerns: ['stress', 'sleep'],
    papers: [
      {
        title: 'GABA intake from a whey protein hydrolysate reduces the time to fall asleep',
        journal: 'Journal of Nutritional Science and Vitaminology',
        year: 2014,
        studyType: 'rct',
        sampleSize: 40,
        durationWeeks: 4,
        keyFinding:
          '100mg GABAの就寝前摂取で入眠潜時が有意に短縮（p<0.05）。深睡眠の増加も確認',
      },
      {
        title: 'Orally administered GABA reduces psychological stress and improves sleep quality',
        journal: 'Biofactors',
        year: 2012,
        studyType: 'rct',
        sampleSize: 63,
        durationWeeks: 4,
        keyFinding:
          'GABA 100mg摂取でストレス負荷後のα波増加とコルチゾール応答の軽減が確認',
      },
    ],
    dosageMin: 100,
    dosageMax: 300,
    dosageUnit: 'mg/日',
    timing: '就寝30〜60分前、またはストレスを感じる前に摂取',
    duration: '急性効果（単回摂取）から確認されている。継続摂取でより安定した効果',
    sideEffects: ['高用量で軽い眠気・めまい', '基本的に安全性が高い'],
    contraindications: ['降圧薬・鎮静薬との相互作用の可能性。服用中の方は医師に相談'],
    products: [
      {
        name: 'GABA 250mg',
        brand: 'NOW Foods',
        platform: 'iherb',
        url: 'https://iherb.com',
        priceJpy: 2000,
        dosageMg: 250,
        rank: 1,
        reasonJa: '論文使用量100〜300mgの範囲内。NOW Foodsは品質管理が確立されており過剰摂取のリスクが低い',
        highlight: '入眠補助',
        monthlyCostJpy: 2000,
      },
    ],
    axisScores: { antiAging: 1, skin: 0, cognitive: 3, stress: 7, sleep: 7, immunity: 1, metabolism: 1 },
    updatedAt: '2026-04-15',
  },

  // ─── 美白・スキンケア成分（追加） ────────────────────────────────────────

  {
    slug: 'arbutin',
    nameJa: 'α-アルブチン',
    nameEn: 'Alpha-Arbutin',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: 'チロシナーゼ阻害によるメラニン産生抑制がRCTで確認されている美白成分',
    description:
      'α-アルブチンはハイドロキノンの配糖体で、チロシナーゼ（メラニン合成の鍵酵素）を競合的に阻害することでメラニン産生を抑制する。ハイドロキノンより刺激が少なく安全性プロファイルが優秀。日本の化粧品に広く使用されており、シミ・肝斑・色素沈着への効果がRCTで確認されている。',
    concerns: ['spots', 'skin-aging', 'uv-damage'],
    papers: [
      {
        title: 'The effect of alpha-arbutin as a skin whitening agent: a systematic review',
        journal: 'Journal of Cosmetic Dermatology',
        year: 2021,
        studyType: 'meta-analysis',
        sampleSize: 486,
        durationWeeks: 12,
        keyFinding:
          'α-アルブチン外用でメラニン指数・ITA値（肌の明るさ）が有意に改善。プラセボとの差は明確（p<0.001）',
      },
      {
        title: 'Comparative study of alpha-arbutin vs kojic acid in melasma treatment',
        journal: 'International Journal of Dermatology',
        year: 2017,
        studyType: 'rct',
        sampleSize: 52,
        durationWeeks: 16,
        keyFinding:
          'α-アルブチン2%がコウジ酸1%と同等の肝斑改善効果を示し、かつ刺激性が有意に少なかった',
      },
    ],
    dosageMin: 1,
    dosageMax: 2,
    dosageUnit: '% 濃度',
    timing: '朝晩使用可能。日焼け止めとの併用で効果が最大化する',
    duration: '8〜16週間の継続で色素改善効果が現れる研究が多い',
    sideEffects: ['基本的に刺激が少なく安全性が高い', 'まれに接触皮膚炎'],
    contraindications: ['アルブチンアレルギー（非常に稀）'],
    products: [
      {
        name: 'Alpha Arbutin 2% + HA',
        brand: 'The Ordinary',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 1500,
        rank: 1,
        reasonJa: '2%濃度はRCTで使用された有効濃度。ヒアルロン酸との組み合わせで保湿しながら美白ケアが可能',
        highlight: '美白の定番',
        monthlyCostJpy: 1500,
      },
    ],
    axisScores: { antiAging: 2, skin: 8, cognitive: 0, stress: 0, sleep: 0, immunity: 1, metabolism: 0 },
    updatedAt: '2026-04-15',
  },

  {
    slug: 'kojic-acid',
    nameJa: 'コウジ酸',
    nameEn: 'Kojic Acid',
    evidenceRank: 'A',
    usageType: 'topical',
    tagline: 'チロシナーゼ阻害による美白効果がRCTで確認されている麹由来成分',
    description:
      'コウジ酸は麹菌（Aspergillus oryzae）が産生するチロシナーゼ阻害物質。メラニン合成の鍵酵素を阻害することでシミ・肝斑・色素沈着を改善する。日本では医薬部外品として認可されており、美白化粧品に広く使用されている。ハイドロキノンより刺激が少ない代替として位置付けられている。',
    concerns: ['spots', 'uv-damage'],
    papers: [
      {
        title: 'A double-blind randomized trial of 1% kojic acid cream in the treatment of melasma',
        journal: 'Journal of the American Academy of Dermatology',
        year: 2019,
        studyType: 'rct',
        sampleSize: 60,
        durationWeeks: 12,
        keyFinding:
          '1%コウジ酸クリームで肝斑のMASIスコアが有意に低下（p<0.05）。忍容性も良好',
      },
      {
        title: 'Kojic acid combined with glycolic acid: efficacy in hyperpigmentation',
        journal: 'Cutis',
        year: 2008,
        studyType: 'rct',
        sampleSize: 40,
        durationWeeks: 12,
        keyFinding:
          'コウジ酸＋グリコール酸の組み合わせでメラニン指数の有意な改善。相乗効果が示唆された',
      },
    ],
    dosageMin: 0.5,
    dosageMax: 2,
    dosageUnit: '% 濃度',
    timing: '朝晩使用可能。日焼け止めとの併用が必須',
    duration: '8〜12週間の継続で色素改善効果が現れる研究が多い',
    sideEffects: ['接触皮膚炎（5〜10%の使用者で報告）', '長期高濃度使用で一時的な赤み'],
    contraindications: ['コウジ酸アレルギーの方', '高濃度製品は刺激が出やすい'],
    products: [
      {
        name: 'Kojic Acid + Vitamin C Brightening Serum',
        brand: 'TruSkin',
        platform: 'amazon',
        url: 'https://amazon.co.jp',
        priceJpy: 2800,
        rank: 1,
        reasonJa: 'コウジ酸＋ビタミンCの組み合わせはRCTで相乗効果が示されており、1本でシミの複数メカニズムにアプローチできる',
        highlight: '美白成分の定番',
        monthlyCostJpy: 2800,
      },
    ],
    axisScores: { antiAging: 2, skin: 7, cognitive: 0, stress: 0, sleep: 0, immunity: 1, metabolism: 0 },
    updatedAt: '2026-04-15',
  },
]

export const concerns: Concern[] = [
  {
    slug: 'skin-aging',
    nameJa: '肌の老化',
    emoji: '🌿',
    category: 'skin',
    description: 'コラーゲン減少・くすみ・ハリの低下など、肌の経年変化に関わるエビデンスを確認した成分一覧',
    ingredientSlugs: ['collagen-peptide', 'niacinamide', 'omega3', 'coq10', 'nmn', 'resveratrol'],
  },
  {
    slug: 'wrinkles',
    nameJa: 'シワ・たるみ',
    emoji: '💆',
    category: 'skin',
    description: '皮膚の弾力・ハリへの関与が研究で示されている成分一覧',
    ingredientSlugs: ['collagen-peptide', 'niacinamide', 'retinol', 'retinal', 'bakuchiol'],
  },
  {
    slug: 'sleep',
    nameJa: '睡眠の質',
    emoji: '🌙',
    category: 'sleep',
    description: '睡眠の質・入眠・睡眠時間への関与が研究で示されている成分一覧',
    ingredientSlugs: ['melatonin', 'glycine', 'magnesium', 'l-theanine', 'gaba', 'ashwagandha'],
  },
  {
    slug: 'stress',
    nameJa: 'ストレス・不安',
    emoji: '🧘',
    category: 'body',
    description: 'コルチゾール・ストレス応答への関与が研究で示されている成分一覧',
    ingredientSlugs: ['ashwagandha', 'l-theanine', 'magnesium', 'gaba'],
  },
  {
    slug: 'fatigue',
    nameJa: '疲れやすい',
    emoji: '⚡',
    category: 'body',
    description: '抗疲労・エネルギー産生への関与が研究で示されている成分一覧',
    ingredientSlugs: ['coq10', 'creatine', 'magnesium', 'ashwagandha', 'glycine', 'nmn'],
  },
  {
    slug: 'cognitive',
    nameJa: '認知・集中力',
    emoji: '🧠',
    category: 'cognitive',
    description: '認知機能・集中力・記憶力への関与が研究で示されている成分一覧',
    ingredientSlugs: ['omega3', 'creatine', 'l-theanine'],
  },
  {
    slug: 'inflammation',
    nameJa: '体の慢性炎症',
    emoji: '🔥',
    category: 'body',
    description: 'Inflammaging（老化性炎症）・炎症マーカーへの関与が研究で示されている成分一覧',
    ingredientSlugs: ['omega3', 'vitamin-d', 'coq10', 'resveratrol'],
  },
  {
    slug: 'gut',
    nameJa: '腸内環境',
    emoji: '🌱',
    category: 'gut',
    description: '腸内フローラ・腸のバリア機能への関与が研究で示されている成分一覧',
    ingredientSlugs: ['probiotics'],
  },
  {
    slug: 'immunity',
    nameJa: '免疫機能',
    emoji: '🛡️',
    category: 'immunity',
    description: '免疫応答・感染リスクへの関与が研究で示されている成分一覧',
    ingredientSlugs: ['vitamin-d', 'probiotics', 'vitamin-c-oral', 'zinc'],
  },
  {
    slug: 'spots',
    nameJa: 'シミ・色素沈着',
    emoji: '✨',
    category: 'skin',
    description: 'メラニン産生・色素沈着への関与が研究で示されている成分一覧',
    ingredientSlugs: ['arbutin', 'niacinamide', 'vitamin-c-topical', 'azelaic-acid', 'kojic-acid', 'glycolic-acid'],
  },
  {
    slug: 'barrier',
    nameJa: 'バリア機能・乾燥',
    emoji: '🏔️',
    category: 'skin',
    description: '角質層の水分保持・経皮水分蒸散量（TEWL）への関与が研究で示されている成分一覧',
    ingredientSlugs: ['ceramide', 'hyaluronic-acid', 'niacinamide'],
  },
  {
    slug: 'dry-skin',
    nameJa: '乾燥肌・保湿',
    emoji: '💧',
    category: 'skin',
    description: '皮膚の水分量・保湿力への関与が研究で示されている成分一覧',
    ingredientSlugs: ['ceramide', 'hyaluronic-acid', 'collagen-peptide'],
  },
  {
    slug: 'acne',
    nameJa: 'ニキビ・肌荒れ',
    emoji: '🌸',
    category: 'skin',
    description: '炎症性ざ瘡・毛穴詰まりへの関与が研究で示されている成分一覧',
    ingredientSlugs: ['salicylic-acid', 'azelaic-acid', 'niacinamide', 'zinc', 'retinal'],
  },
  {
    slug: 'pores',
    nameJa: '毛穴・テクスチャー',
    emoji: '🔬',
    category: 'skin',
    description: '毛穴の目立ちにくさ・肌のキメへの関与が研究で示されている成分一覧',
    ingredientSlugs: ['salicylic-acid', 'glycolic-acid', 'niacinamide', 'retinol'],
  },
  {
    slug: 'uv-damage',
    nameJa: '光老化・UVダメージ',
    emoji: '☀️',
    category: 'skin',
    description: '紫外線による皮膚ダメージ・光老化への対策に関するエビデンスを持つ成分一覧',
    ingredientSlugs: ['retinol', 'vitamin-c-topical', 'niacinamide', 'arbutin', 'kojic-acid', 'resveratrol'],
  },
  {
    slug: 'hair',
    nameJa: '髪・爪',
    emoji: '💎',
    category: 'body',
    description: '毛髪・爪の健康への関与が研究で示されている成分一覧',
    ingredientSlugs: ['biotin', 'zinc'],
  },
  {
    slug: 'bone',
    nameJa: '骨密度・関節',
    emoji: '🦴',
    category: 'body',
    description: '骨密度・骨強度への関与が研究で示されている成分一覧',
    ingredientSlugs: ['vitamin-d', 'collagen-peptide'],
  },
]

export function getIngredient(slug: string): Ingredient | undefined {
  return ingredients.find((i) => i.slug === slug)
}

export function getConcern(slug: string): Concern | undefined {
  return concerns.find((c) => c.slug === slug)
}

export function getIngredientsByConcern(concernSlug: string): Ingredient[] {
  const concern = getConcern(concernSlug)
  if (!concern) return []
  return concern.ingredientSlugs
    .map((slug) => getIngredient(slug))
    .filter((i): i is Ingredient => !!i)
    .sort((a, b) => {
      const rankOrder: Record<string, number> = { S: 0, A: 1, B: 2, C: 3 }
      return rankOrder[a.evidenceRank] - rankOrder[b.evidenceRank]
    })
}

export const evidenceRankConfig = {
  S: {
    label: 'S',
    description: 'メタ解析・システマティックレビュー',
    color: 'evidence-s',
    note: '最も信頼度が高い研究形式',
  },
  A: {
    label: 'A',
    description: 'RCT（ランダム化比較試験）',
    color: 'evidence-a',
    note: '厳密な比較実験による検証',
  },
  B: {
    label: 'B',
    description: 'コホート研究・大規模観察研究',
    color: 'evidence-b',
    note: '長期追跡による関連性の確認',
  },
  C: {
    label: 'C',
    description: '小規模研究・動物実験段階',
    color: 'evidence-c',
    note: 'ヒトでの大規模検証が不十分',
  },
} as const
